services:
  db:
    image: postgres:17.2
    healthcheck:
      test: ["CMD", "pg_isready", "--username=postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/posgtresql/data

volumes:
  db-data:
